# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-26 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='the_author',
        ),
        migrations.AddField(
            model_name='author',
            name='the_book',
            field=models.ManyToManyField(related_name='authors', to='books.Book'),
        ),
    ]
