# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191126_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='Temp', max_length=255),
        ),
    ]
