# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
