# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_auto_20191126_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='TEMP', max_length=255),
        ),
    ]
