# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-11-26 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20191126_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='uploaded_books',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
